# Generated by Django 5.0.6 on 2024-05-17 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='schedule_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='courses.courseschedule'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('schedule_id',)},
        ),
    ]
