# Generated by Django 5.0.6 on 2024-05-17 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_schedule_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='schedule_id',
            new_name='schedule',
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('schedule',)},
        ),
    ]
